#2668: Added support for collections and maps with a no-args constructor
mapstruct/mapstruct pull request #2671
Opened 2021-11-23 22:57 UTC by Zegveld

Added support for collections and maps with a no-args constructor
Added a compiler error in case of a collection or map without either a no-arg constructor or a copy constructor.

2021-12-27 16:45 UTC, Zegveld commented
This should fix #2668.
It allows support for more collection types. (e.g. other implementations of the java.util collection framework).

2022-01-22 13:04 UTC, filiphr requested changes
The functionality looks good @Zegveld. I've left some comments about the implementation, more specifically the 2 new parameters in the `Type`. I don't think that they need to be on the `Type`.

2022-01-22 13:58 UTC, Zegveld commented on processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
> +    private boolean hasNoArgsConstructor;
moved this with https://github.com/mapstruct/mapstruct/pull/2671/commits/b64c708f4e65c7551a44886669f3fd070ea5941e

2022-01-22 14:23 UTC, filiphr commented on processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
> +    private boolean hasNoArgsConstructor;
Thanks

2022-01-22 14:25 UTC, filiphr approved these changes
Looks great @Zegveld. I pushed one small change for using a method invocation. We can squash and merge once the CI is done.

If you are merging it, please remove my co-authorship, you did all the work 😉 .

2022-01-28 23:37 UTC, merged