#2686 Add documentation about when mappers are injected
mapstruct/mapstruct pull request #2702
Opened 2021-12-25 11:27 UTC by filiphr

Fixes #2686

2021-12-27 13:22 UTC, Zegveld requested changes
I think it is still to ambiguous, see comment.

2021-12-27 13:22 UTC, Zegveld commented on documentation/src/main/asciidoc/chapter-4-retrieving-a-mapper.asciidoc
> +The generated mapper will inject all classes defined in the **uses** attribute and MapStruct has detected that they are actually used on some of the mappings.
does the injection also take place if a static method is used from the defined class?

Perhaps a better wording would be:
`The generated mapper will inject classes defined in the **uses** attribute if MapStruct has detected that it needs to use an instance of it for a mapping.`

2022-01-15 09:33 UTC, filiphr commented
You are right @Zegveld. Your suggestion is way better. I've added that

2022-01-15 10:50 UTC, Zegveld approved these changes

2022-01-18 17:22 UTC, merged

2022-01-18 17:22 UTC, filiphr commented
Thanks for the review @Zegveld