2709 Corrected description for example demonstrating default expression
mapstruct/mapstruct pull request #2710
Opened 2021-12-27 18:17 UTC by Goni-Dev

2022-01-15 09:53 UTC, filiphr requested changes
Thanks a lot @Goni-Dev.

I've added a suggestion change since the `defaultExpression` is also used when presence checks are used, either through presence checks on the bean itself or using the `@Condition`.

What do you think about my proposal?

2022-01-15 09:53 UTC, filiphr commented on documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
> +The example below demonstrates how a default expression can be used to set a value when the source attribute is `null`:
```suggestion
The example below demonstrates how a default expression can be used to set a value when the source attribute is not present (e.g. is `null`):
```

2022-01-23 15:36 UTC, Goni-Dev commented
Thanks a lot for reviewing. 
I'm totally fine with the proposal.

2022-01-23 16:26 UTC, merged

2022-01-23 16:26 UTC, filiphr commented
Thanks @Goni-Dev