#3037 Make @ValueMapping and @ValueMappings support combinations
mapstruct/mapstruct pull request #3043
Opened 2022-10-02 09:32 UTC by chenzijia12300

Try to implement #3037

2022-10-02 09:58 UTC, filiphr requested changes
Thanks @chenzijia12300. The implementation looks good. However, I think that we need to change the location of the test a bit.

We should not touch the `CompositionTest`. Instead I would suggest creating a new `ValueCompositionTest` in a new package `org.mapstruct.ap.test.value.composition` and also put the `CustomValueAnnotation` and `ValueMappingCompositionMapper` in that package.

2022-10-02 09:58 UTC, filiphr commented on processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/value/CustomValueAnnotation.java
> +})
Let's use `ValueMapping` only here.

e.g.

```suggestion
@ValueMapping(source = "EXTRA", target = "SPECIAL"),
@ValueMapping(source = MappingConstants.ANY_REMAINING, target = "DEFAULT")
```

2022-10-02 11:16 UTC, chenzijia12300 commented on processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/value/CustomValueAnnotation.java
> +})
Have modified

2022-10-02 11:18 UTC, chenzijia12300 commented
@filiphr Thank you for pointing it out, I have made the changes  ;D

2022-10-02 19:22 UTC, sjaakd approved these changes

2022-10-03 19:11 UTC, filiphr commented
Everything looks good @chenzijia12300, I was about to merge this. However, I remembered that perhaps it will be good to add an example to the documentation as well. Can you please add a new section to the [Mapping Values](https://mapstruct.org/documentation/stable/reference/html/#mapping-enum-types) chapter?

2022-10-04 02:36 UTC, chenzijia12300 commented
@filiphr   No problem, I'll try to add an example to the documentation

2022-10-12 19:06 UTC, sjaakd approved these changes

2022-11-03 22:21 UTC, merged

2022-11-03 22:22 UTC, filiphr commented
Thanks @chenzijia12300