[WIP] translate the guide reference into Chinese
mapstruct/mapstruct pull request #3050
Opened 2022-10-08 14:34 UTC by Qomolang

It is a BETA version which means the translation style is not 100% equal to the English version, but it may be very useful for Chinese programmer

2023-09-28 14:01 UTC, Qomolang commented
@filiphr hi~, could you have a look at this pr when you have time please~~

2023-09-30 09:28 UTC, filiphr commented
I will try @Qomolang. I'll try to bring this in with the 1.6 release. The only thing that I am afraid with this is the fact that it will be lagging behind the main english documentation.

2023-10-04 05:41 UTC, Qomolang commented
> I will try @Qomolang. I'll try to bring this in with the 1.6 release. The only thing that I am afraid with this is the fact that it will be lagging behind the main english documentation.

> I understand your concern. I would try to check the English documentation once every month. Also, you can @me when the English docs change every time you notice

2024-07-15 12:38 UTC, thunderhook requested changes
Thanks for your work on this @Qomolang!

I took the time to translate it via deepl and compared it to the recently released documentation. Some nitpicks, some missing sections. Otherwise: good work!

2024-07-15 12:38 UTC, thunderhook commented on documentation/src/main/asciidoc/chinese/chapter-6-集合的映射.asciidoc
> +集合类型（List、Set等）的映射和bean类型的映射采用相同方式，都是在mapper接口中定义方法，并指定要映射的source类型和target类型。MapStruct支持来自 http://docs.oracle.com/javase/tutorial/collections/intro/index.html[Java Collection Framework] 中广泛的iterable类
```suggestion
集合类型（`List`、`Set`等）的映射和bean类型的映射采用相同方式，都是在mapper接口中定义方法，并指定要映射的source类型和target类型。MapStruct支持来自 http://docs.oracle.com/javase/tutorial/collections/intro/index.html[Java Collection Framework] 中广泛的iterable类型。
```

2024-07-15 12:38 UTC, thunderhook commented on documentation/src/main/asciidoc/chinese/chapter-8-值的映射.asciidoc
> +
Would you mind also adding the THROW_EXCEPTION options introduced here:

https://github.com/mapstruct/mapstruct/commit/62c7ce1cdf0ccc5528dca84decaf07cbecadaed4#diff-aaca9b52e434c4fb6940e4405327fe73da5f3438442109c4c8c6f858c0d6ddee

2024-07-15 12:38 UTC, thunderhook commented on documentation/src/main/asciidoc/chinese/chapter-8-值的映射.asciidoc
> +也支持注册自定义策略，更多信息请参见 <<custom-enum-transformation-strategy>>
Would you be so kind and add the new section: 

https://github.com/mapstruct/mapstruct/commit/6a394ad466b5bda8b17e2406b56be34be3312e21#diff-aaca9b52e434c4fb6940e4405327fe73da5f3438442109c4c8c6f858c0d6ddee

2024-07-15 12:40 UTC, thunderhook commented on documentation/src/main/asciidoc/chinese/mapstruct参考指南.asciidoc
> +
@filiphr WDYT?

2024-07-21 10:31 UTC, filiphr commented on documentation/src/main/asciidoc/chinese/mapstruct参考指南.asciidoc
> +
That sounds reasonable to me @thunderhook

2025-02-09 10:04 UTC, Qomolang commented on documentation/src/main/asciidoc/chinese/chapter-10-高级映射选项.asciidoc
> +下例展示了两个source属性如何映射为target属性：
oh, it's an obvious error, thanks for pointing out it

2025-02-09 10:17 UTC, Qomolang commented on documentation/src/main/asciidoc/chinese/chapter-10-高级映射选项.asciidoc
> +.Mapping method with default values and constants
I had asked some friends about this, some thought keep the headers was better:
1. it helps to find corresponding English version paragraph
2. headers do not affect understanding much, because the viewers can use the context

I have post this translation on my blog, no one have comment for this, but I am still hesitated about whether translating headers, I will continue to keep an eye on it

2025-02-09 11:21 UTC, Qomolang commented on documentation/src/main/asciidoc/chinese/chapter-11-映射配置复用.asciidoc
> +* `EXPLICIT` （默认）：如果target映射方法有@InheritConfiguration注解，并且source类型是原型方法source类型的子类，target类型也是原型方法中target类型的子类（详见 <<mapping-configuration-inheritance>> ），那么仅配置会被继承。
Meticulous work！it's a missing

2025-02-09 11:54 UTC, Qomolang commented on documentation/src/main/asciidoc/chinese/chapter-13-using-mapstruct-spi.asciidoc
> +The `CustomAccessorNamingStrategy` makes use of the `DefaultAccessorNamingStrategy` (also available in mapstruct-processor) and relies on that class to leave most of the default behaviour unchanged.
when I changed the format from markdown to asciidoc, some version problem happened, now it's ok

2025-02-09 12:20 UTC, Qomolang commented on documentation/src/main/asciidoc/chinese/mapstruct参考指南.asciidoc
> +
it's added in the “中译前言” part

2025-02-09 12:27 UTC, Qomolang commented on documentation/src/main/asciidoc/chinese/chapter-4-检索mapper.asciidoc
> +另外，MapStruct生成的mapper都是无状态且类型安全的，因此您可以同时安全地用多线程安全地访问这些mapper。
it's a translation problem, thread-safe is translated into "multi-threaded security"

2026-06-02 19:54 UTC, filiphr commented
Since none of us understands chinese, we have decided not to include the chinese guide in our code. It should be hosted outside of MapStruct.

2026-06-02 19:54 UTC, closed without merging