#2863 Add validation of String type to @TargetPropertyName
mapstruct/mapstruct pull request #3064
Opened 2022-10-30 11:17 UTC by paparadva

Check that a parameter annotated with @TargetPropertyName is String and report an error.

With the following mapper:

```java
@Mapper
public interface ErroneousNonStringTargetPropertyNameParameter {

    Employee map(EmployeeDto employee);

    @Condition
    default boolean isNotBlank(String value, @TargetPropertyName int propName) { // propName is int
        return value != null && !value.trim().isEmpty();
    }
}
```

Compilation will fail with this error message:

> error: @TargetPropertyName can only by applied to a String parameter.

2023-04-22 17:58 UTC, filiphr requested changes
The PR is great @paparadva.

I've only left one small comment around the error. You can actually see how it will look better in the error line if the erroneous mapper has the method like:

```java
default boolean isNotBlank(
    String value,
    @TargetPropertyName int propName
) {
        return value != null && !value.trim().isEmpty();
}
```

2023-04-22 17:58 UTC, filiphr commented on processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java
> +                messager.printMessage( method, Message.RETRIEVAL_TARGET_PROPERTY_NAME_WRONG_TYPE );
We can actually pass the annotation mirror from the `@TargetPropertyName` here as well. We also should use the parameter name element for the error element.

e.g.

```java
message.printMessage(
    param.getElement(),
    TargetPropertyNameGem.instanceOn( param.getElement() ).mirror() ),
    Message. RETRIEVAL_TARGET_PROPERTY_NAME_WRONG_TYPE
);
```

2023-05-21 12:19 UTC, paparadva commented
I updated isValidPresenceCheckMethod, the error message now points to propName:
```
    default boolean isNotBlank(String value, @TargetPropertyName int propName) {
                                             ^
```

2023-05-21 20:21 UTC, merged

2023-05-21 20:21 UTC, filiphr commented
Thanks for your work on this @paparadva