Add support for globally defining nullValueMapMappingStrategy and nullValueIterableMappingStrategy
mapstruct/mapstruct pull request #3068
Opened 2022-11-03 20:47 UTC by filiphr

Fixes #2953

2022-11-04 14:21 UTC, Zegveld requested changes
Looks good to me, just a minor thing about missing `IssueKey` annotations at the tests.

2022-11-04 14:21 UTC, Zegveld commented on processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/NullValueIterableMappingStrategyTest.java
> +public class NullValueIterableMappingStrategyTest {
missing the issuekey annotation here I believe.

2022-11-04 14:21 UTC, Zegveld commented on processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/NullValueMapMappingStrategyTest.java
> +public class NullValueMapMappingStrategyTest {
missing the issuekey annotation here I believe.

2022-11-12 18:26 UTC, Zegveld approved these changes

2022-11-13 13:22 UTC, merged

2023-09-21 09:17 UTC, mikybars commented
Somebody could explain why this feature is not present in the latest release?

2023-09-30 09:08 UTC, filiphr commented
The feature is not present in 1.5 because the fix version of #2953 is 1.6