fix: detect collection adders using Iterable setter/getter
mapstruct/mapstruct pull request #3130
Opened 2023-01-02 08:59 UTC by sranka

Closes #3126

The code herein fixes the detection of collection adders to count with a more generic `Iterable` as a setter argument (or a getter return value). As consequence, a lombok generated builder setter fluent method:
```
public LombokImmutablePathBuilder edges(Iterable<? extends String> edges) {
  // ...
  return this;
}
```
is now also considered as a candidate for searching of an associated adder:
```
public LombokImmutablePathBuilder addEdge(String edge) {
  // ...
  return this;
}
```

Using the adders directly has a performance benefit. The mapper implementation then does not need to create intermediary ArrayList values to map collection properties. For example, in place of this code that always creates an intermediary ArrayList to be passed to a setter:

```java
...
ActionRule.ActionRuleBuilder actionRule = ActionRule.builder();
if (actionRules.getCostList() != null) {
    actionRule.costs(this.costListToCostIterable(actionRules.getCostList()));
}
...
protected Iterable<Cost> costListToCostIterable(List<b.Cost> list) {
    if (list == null) {
        return null;
    } else {
        ArrayList<Cost> iterable = new ArrayList(list.size());
        Iterator var3 = list.iterator();

        while(var3.hasNext()) {
            com.goeuro.search2.model.proto.Cost cost = (com.goeuro.search2.model.proto.Cost)var3.next();
            iterable.add(this.costMapper.map(cost));
        }

        return iterable;
    }
}
```

The mapper code then generates a much more optimal:
```java
ActionRule.ActionRuleBuilder actionRule = ActionRule.builder();
if (actionRules.getCostList() != null) {
    Iterator var3 = actionRules.getCostList().iterator();

    while(var3.hasNext()) {
        Cost costList = (Cost)var3.next();
        actionRule.addCost(this.costMapper.map(costList));
    }
}
```

2023-03-17 09:20 UTC, filiphr requested changes
I've left a comment on the `LombokBuilderAccessorNamingStrategy`. I think that the solution for this is fine (i.e. support adder methods for iterables). However, I would like to decouple this from Lombok entirely.

Can you also simplify the test classes a bit. This can be easily reproduced by having a class that looks like:

```java
public class ImnutablePath {
    private final List<String> edges = new ArrayList<>();

    public Iterable<String> getEdges() {
        return edges;
    }

    public void setEdges(Iterable<String> edges) {
        this.edges.clear();
        for(String edge: edges) {
            this.edges.add(edge.toUpperCase());
        }
    }

    public void addEdge(String edge) {
        this.edges.add(edge);
    }
}
```

The tests should also be moved in the `org.mapstruct.ap.test.collection.adder.AdderTest`

2023-03-17 09:20 UTC, filiphr commented on processor/src/test/java/org/mapstruct/ap/test/builder/lombok/LombokBuilderAccessorNamingStrategy.java
I don't understand the use of this class. There is an easy workaround for this if you use `@Singular("add<singular")`. If we are going in the territory of supporting `@Singular` properly then we need to also support something like `@Singular("custom")`. 

I would prefer that we do not go in that direction and only perhaps support adders for iterables as well.

2023-03-17 09:20 UTC, filiphr commented on processor/src/test/java/org/mapstruct/ap/test/builder/lombok/PathMapper.java
> +    })
This is obsolete. MapStruct is going to map this implicitly

2023-04-22 20:26 UTC, filiphr commented
@sranka you don't need to do anything on this PR. I believe that PR #3166 is going to solve the problem

2023-04-23 18:48 UTC, sranka commented
@filiphr yeah, it looks similar, closing this PR

2023-04-23 18:48 UTC, closed without merging