Improve line location report for invalid qualifier for SubclassMapping
mapstruct/mapstruct pull request #3204
Opened 2023-03-18 12:32 UTC by EvaristeGalois11

Fix #3202 

I had to remove one of the `@SubclassMapping` annotations from the erroneous mappers because otherwise the tests would fail.

It seems that if more than one annotations of the same type as `AnnotationMirror` are present on the mapping method the compiler will fallback to emit the error on the method itself. Eclipse compiler seems to work fine regardless of the number of annotations. Is this an already known issue?

2023-04-16 17:13 UTC, filiphr requested changes
Thanks @EvaristeGalois11. The PR looks great, only one small cosmetic comment regarding the prefix `Gem` in fields and variables. We are usually not using it in other places, e.g. `MappingOptions`, `BeanMappingOptions`.

>It seems that if more than one annotations of the same type as `AnnotationMirror` are present on the mapping method the compiler will fallback to emit the error on the method itself. Eclipse compiler seems to work fine regardless of the number of annotations. Is this an already known issue?

This is indeed a known issue. I think that newer Java compiler versions have fixed this. The eclipse compiler always worked fine. You don't need to remove anything from the code you can use the `alternativeLine` in the `@Diagnostic`. You can actually remove in one place and leave in the other, to make sure that we really do report in the right place in both cases. As an example with this similar problem is `AnnotateWithTest#mapperWithIdenticalAnnotationRepeated`

2023-04-16 17:13 UTC, filiphr commented on processor/src/main/java/org/mapstruct/ap/internal/model/source/SubclassMappingOptions.java
> +    private final SubclassMappingGem subclassMappingGem;
Let's name this `subclassMapping`. We are not adding the `Gem` prefix to fields and variables. e.g. have a look at `MappingOptions`

2023-04-16 22:07 UTC, EvaristeGalois11 commented
Thank you @filiphr for your feedback! I have updated the PR with what you said.

I had to change the `copyForInverseInheritance` method a bit because i couldn't find a combination of variables name that wasn't awkard, I hope it isn't a problem.

2023-04-22 16:16 UTC, merged

2023-04-22 16:16 UTC, filiphr commented
Thanks @EvaristeGalois11