simplified some expressions, redundant expressions removed
mapstruct/mapstruct pull request #3292
Opened 2023-05-29 21:59 UTC by anton-erofeev

2023-06-16 09:01 UTC, filiphr requested changes
Thanks for this cleanups @anton-erofeev. I only have one small remark, see my comment

2023-06-19 11:49 UTC, anton-erofeev commented on processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java
> +                            typeMirror -> ctx.getTypeUtils().isSameType(typeMirror, subClassOption.getSource()));
ok, I reverted this change, thanks

2023-07-08 15:48 UTC, filiphr commented
@anton-erofeev seems like there are some formatting issues. Can you have a look at it please?

2023-07-19 10:03 UTC, anton-erofeev commented
> @anton-erofeev seems like there are some formatting issues. Can you have a look at it please?
updated but it looks like I can't run checks

2023-07-29 13:32 UTC, filiphr commented
You are contributing for the first time @anton-erofeev and that's why the checks don't run automatically. I need to approve them in order for them to run. Just did that, if everything is OK, we'll merge this. For your next contributions this won't be necessary.

2023-08-01 07:18 UTC, filiphr commented on processor/src/test/java/org/mapstruct/ap/test/nestedbeans/HouseDto.java
> +        return Objects.equals(roof, houseDto.roof);
```suggestion
        return Objects.equals( roof, houseDto.roof );
```

2023-08-01 12:17 UTC, merged

2023-08-01 12:17 UTC, filiphr commented
thank @anton-erofeev