#3309 - Add `BeanMapping#unmappedSourcePolicy`
mapstruct/mapstruct pull request #3326
Opened 2023-07-12 23:04 UTC by venkatesh2090

Add support for specifying `unmappedSourcePolicy` similar to `unmappedTargetPolicy` on `BeanMapping`.

2023-07-29 07:45 UTC, filiphr requested changes
Thanks for your work on this @venkatesh2090.

Have a look at my comments. In addition to that, can you please add tests with different policies and also a combination of policy on `@Mapper` and `@BeanMapping` to show that it is being picked up properly

2023-07-29 07:45 UTC, filiphr commented on core/src/main/java/org/mapstruct/BeanMapping.java
> +     * @since
Feel free to add 1.6 here

2023-07-29 07:45 UTC, filiphr commented on core/src/main/java/org/mapstruct/BeanMapping.java
> +    ReportingPolicy unmappedSourcePolicy() default ReportingPolicy.WARN;
Please use `ReportingPolicy.IGNORE` which is the same as the one used `Mapper`

2023-07-29 07:45 UTC, filiphr commented on processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java
> -            if ( method.getOptions().getBeanMapping().isignoreByDefault() ) {
Why is this changed needed? This method is for the unmapped target policy and you are adding functionality for the unmapped source policy. Perhaps the null check on line 1639 is obsolete, but let's try to keep the PRs focused on the main functionality and leave things like this for other PRs

2023-07-29 07:45 UTC, filiphr commented on processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java
> -            if ( method.getOptions().getBeanMapping().isignoreByDefault() ) {
I think that we can leave this as is and then just return 
```java
method.getOptions().getBeanMapping().unmappedSourcePolicy();
```

That makes sure that if it is not set on the bean mapping then the next one will be used.

2023-07-30 08:42 UTC, filiphr requested changes
Thanks for the changes. I've added one last comment and we'll merge once that is done and the build is green

2023-07-30 08:42 UTC, filiphr commented on core/src/main/java/org/mapstruct/BeanMapping.java
> +     * {@link Mapper#unmappedSourcePolicy()} will be applied, using {@link ReportingPolicy#WARN} by default.
```suggestion
     * {@link Mapper#unmappedSourcePolicy()} will be applied, using {@link ReportingPolicy#IGNORE} by default.
```

2023-07-30 10:30 UTC, venkatesh2090 commented
I was refactoring the tests and writing more which broke more stuff. I'll fix it and push it once it's done. FYI here's the error I get during the tests.

```shell
ERROR BeanMappingSourcePolicyMapper.java:20 'nullValueMappingStrategy', 'nullValuePropertyMappingStrategy', 'resultType' and 'qualifiedBy' are undefined in @BeanMapping, define at least one of them.
```

It might take a bit more time. My bad.

2023-07-30 10:45 UTC, venkatesh2090 commented
I did manage to fix it, but I have one concern.

This error message in [Message](https://github.com/mapstruct/mapstruct/blob/main/processor/src/main/java/org/mapstruct/ap/internal/util/Message.java#L27) looks outdated. It is being used in [BeanMappingOptions.isConsistent](https://github.com/mapstruct/mapstruct/blob/main/processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMappingOptions.java#L104) where it checks for more values than the error message points out. The message is inconsistent I think.

2023-08-01 07:13 UTC, filiphr requested changes
Thanks @venkatesh2090, one last comment for the integration tests to pass and we are done. You are right, the error message in the `@BeanMapping` is inconsistent. We can change this in a different PR. The message doesn't need to enumarate all options, we can just say `@BeanMapping` must have at least one option defined

2023-08-01 07:48 UTC, merged

2023-08-01 07:48 UTC, filiphr commented
Thanks @venkatesh2090, this has been integrated into main