Expression or condition
mapstruct/mapstruct pull request #3445
Opened 2023-11-20 19:56 UTC by the-mgi

fixes #3413

2023-11-22 21:55 UTC, thunderhook requested changes
Hi @the-mgi!

Sorry it took so long to review. (now that I see it, 2 days isn't that long 😅 )

Would you be so kind and add a unit test? This would look similar to the[`Issue2668Test`](https://github.com/mapstruct/mapstruct/blob/main/processor/src/test/java/org/mapstruct/ap/test/bugs/_2668/Issue2668Test.java#L23-L42).

Thanks in advance!

2023-11-22 21:55 UTC, thunderhook commented on processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java
> +        else if (gem.expression().hasValue() && gem.conditionQualifiedByName().hasValue()) {
formatting nitpick: please add a whitespace (see the formatter in [CONTRIBUTING.md](https://github.com/mapstruct/mapstruct/blob/main/CONTRIBUTING.md)) - 6 lines beyond there is also a whitespace missing, would be nice if you could also add it there 

(wondering why checkstyle did not fail)

2023-11-23 10:18 UTC, the-mgi commented
test case added, added proper whitespace

2023-11-23 10:48 UTC, the-mgi commented
FYI there is a failing test `mapstruct/processor/src/test/java/org/mapstruct/ap/test/collection/iterabletoset/FruitsMapper.java` on local on main branch, and on expression-or-condition.

2023-11-23 21:30 UTC, thunderhook approved these changes

2023-11-24 05:34 UTC, merged