#3574 Respect only explicit mappings but fail on unmapped source fields
mapstruct/mapstruct pull request #3632
Opened 2024-06-30 12:53 UTC by filiphr

This reverts #2560, because we've decided that `@BeanMapping(ignoreByDefault = true)` should only be applied to target properties and not to source properties. Source properties are anyway ignored, the `BeanMapping#unmappedSourcePolicy` should be used to control what should happen with unmapped source policy

Fixes #3574

2024-07-01 20:18 UTC, thunderhook requested changes
Just a few nit picky notes, and of course Checkstyle makes an appearance 😉

2024-07-01 20:18 UTC, thunderhook commented on documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
> +The example demonstrates how the source properties `time` and `format` are composed into one target property `TimeAndFormat`. Please note that the fully qualified package name is specified because Ma
Attention, I think you changed it here unintentionally (due to an IntelliJ rename)

2024-07-01 20:18 UTC, thunderhook commented on documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
> +The example demonstrates how to use defaultExpression to set an `ID` field if the source field is null, this could be used to take the existing `sourceId` from the source object if it is set, or crea
Attention, I think you changed it here unintentionally (due to an IntelliJ rename)

2024-07-01 20:18 UTC, thunderhook commented on NEXT_RELEASE_CHANGELOG.md
> +Source properties are anyway ignored, the `BeanMapping#unmappedSourcePolicy` should be used to control what should happen with unmapped source policy
nitpick: `anyway ignored` -> `ignored anyway`

2024-07-06 07:11 UTC, filiphr commented
Thanks for the feedback @thunderhook. I've applied the changes

2024-07-06 07:31 UTC, thunderhook approved these changes

2024-07-06 08:31 UTC, merged